name: Build and deploy docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  docs:
    if: github.repository == 'Checkmate-12961/PP'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Final-Season
        uses: actions/checkout@v2
        with:
          path: Final-Season

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Make gradlew executable
        run: 'chmod +x gradlew'
        working-directory: ./Final-Season

      - name: Build docs
        run: './gradlew TeamCode:dokkaHtml'
        working-directory: ./Final-Season

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Final-Season/TeamCode/build/dokka/html
          keep_files: true
          full_commit_message: Publish documentation
